import { ClerkProvider } from "@clerk/nextjs"
import "../../app/globals.css"
import { dark } from "@clerk/themes"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <ClerkProvider
      appearance={{ baseTheme: dark }}
      >
      {children}
      </ClerkProvider>
      </body>
    </html>
  )
}
